### ISSUE TITLE
Drivers 

### ISSUE THREAD

**Issue by Akashchandel27** [ivan-markov-666/Selenium-Custom-Java-Frame#6]
Please add the drivers also in the driver folders. I am not able to execute the code

**Comment by ivan-markov-666** [comment]
**Answer:**
- The drivers should be downloaded and put into the "drivers" folder. This is because there are many driver versions related to your browser version. I am not able to cover all driver versions.
- For more details please refer to web driver official documentation: https://www.selenium.dev/documentation/webdriver/
- Chrome driver can be found (and downloaded from) here: https://chromedriver.chromium.org/downloads
- Gecko (the driver for Firefox) can be found (and downloaded from) here: https://github.com/mozilla/geckodriver/releases

**Please let me know if you have any other questions or issues.**
